### ISSUE TITLE
Error in login - GATEKEEPER

### ISSUE THREAD

**Issue by brunopnogueira92** [germinateplatform/gatekeeper-vue#7]
Hello Everyone,

In advance, thanks so much for your time.

I am trying to enter the gatekeeper web client but when i put the initial user and password (admin, password) returns to me an error: "Server appears to be unavailable."

I see the logs in tomcat and no error was returned.

```
INFO: 
                                      
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@  @@        @@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@        @@@@@@@@@@
@@@@@@@@@@@@@@@@  @@  @@    @@@@@@@@@@
@@@@@@@@@@  @@@@  @@  @@    @@@@@@@@@@
@@@@@@@@@@        @@        @@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@        @@        @@@@@@@@@@
@@@@@@@@@@    @@  @@  @@@@  @@@@@@@@@@
@@@@@@@@@@    @@  @@  @@@@  @@@@@@@@@@
@@@@@@@@@@        @@  @  @  @@@@@@@@@@
@@@@@@@@@@        @@        @@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@  @@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@  Thank you for using jOOQ 3.11.9
                                      
jul 15, 2020 6:23:58 PM org.apache.jasper.servlet.TldScanner scanJars
INFO: At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
jul 15, 2020 6:23:58 PM jhi.gatekeeper.server.ApplicationListener logMessage
INFO: 
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@#################%@@@@@@@@@@@@@@@@%////////@@@
@@@@@@@@@@@#####################@@@@@@@@@@@@@@(///////#@@@@
@@@@@@@@@@#######################@@@@@@@@@@@@////////@@@@@@
@@@@@@@@@((((((((@@@@@@@@@@@@@@@@@@@@@@@@@@@////////@@@@@@@
@@@@@@@@((((((((@@@@@@@@@@@@@@@@@@@@@@@@@@@////////@@@@@@@@
@@@@@@@((((((((@@@@@@@@@@@@@@@@@@@@@@@@@@@////////@@@@@@@@@
@@@@@&((((((((@@@@@@@@@@@@@@@@@@@@@@@@@@@////////@@@@@@@@@@
@@@@#(((((((/@@@@@@@@@@@@@@@@@@@@@@@@@@%##//////@@@@@@@@@@@
@@@((((((((@@@@@@@@@@@@@@@@@@@@@@@@@@@%####///(@@@@@@@@@@@@
@@@(((((((@@@@@@@@@@@@@@@@@@@@@@@@@@@(######/(@@@@@@@@@@@@@
@@@(((((((@@@@@@@@,,,,,,,,,,,,,,,*@@@@#######@@@@@@@@@@@@@@
@@@((((((((@@@@@@@@,,,,,,,,,,,,,***@@@%#######@@@@@@@@@@@@@
@@@@/(((((((#@@@@@@@,,,,,,,,,,,*****@@@%#######@@@@@@@@@@@@
@@@@@@((((((((@@@@@@@@@@@@@@@********@@@@#######@@@@@@@@@@@
@@@@@@@((((((((@@@@@@@@@@@@@********@@@@@@########@@@@@@@@@
@@@@@@@@((((((((@@@@@@@@@@@********@@@@@@@@########@@@@@@@@
@@@@@@@@@((((((((@@@@@@@@@********@@@@@@@@@@########@@@@@@@
@@@@@@@@@@((((((((///////////////@@@@@@@@@@@@########@@@@@@
@@@@@@@@@@@((((((((////////////*@@@@@@@@@@@@@@%#######%@@@@
@@@@@@@@@@@@@(((((((//////////@@@@@@@@@@@@@@@@@%########@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

               Thanks for using Gatekeeper!

jul 15, 2020 6:23:59 PM jhi.gatekeeper.server.Database init
INFO: RUNNING FLYWAY on: gatekeeper
jul 15, 2020 6:23:59 PM org.flywaydb.core.internal.util.VersionPrinter info
INFO: Flyway 4.0.2 by Boxfuse
jul 15, 2020 6:23:59 PM org.flywaydb.core.internal.dbsupport.DbSupportFactory info
INFO: Database: jdbc:mysql://localhost:3306/gatekeeper?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Europe/London (MySQL 8.0)
jul 15, 2020 6:23:59 PM org.flywaydb.core.internal.command.DbMigrate info
INFO: Current version of schema `gatekeeper`: 4.0.0
jul 15, 2020 6:23:59 PM org.flywaydb.core.internal.command.DbMigrate info
INFO: Schema `gatekeeper` is up to date. No migration necessary.
jul 15, 2020 6:23:59 PM org.flywaydb.core.internal.metadatatable.MetaDataTableImpl info
INFO: Repair of failed migration in metadata table `gatekeeper`.`schema_version` not necessary. No failed migration detected.
jul 15, 2020 6:23:59 PM org.flywaydb.core.internal.command.DbRepair info
INFO: Successfully repaired metadata table `gatekeeper`.`schema_version` (execution time 00:00.017s).
jul 15, 2020 6:23:59 PM org.flywaydb.core.internal.command.DbRepair info
INFO: Manual cleanup of the remaining effects the failed migration may still be required.
jul 15, 2020 6:23:59 PM jhi.gatekeeper.server.Database init
INFO: RUNNING VIEW/PROCEDURE CREATION SCRIPT!
jul 15, 2020 6:24:00 PM org.jooq.tools.JooqLogger info
INFO: 
                                      
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@  @@        @@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@        @@@@@@@@@@
@@@@@@@@@@@@@@@@  @@  @@    @@@@@@@@@@
@@@@@@@@@@  @@@@  @@  @@    @@@@@@@@@@
@@@@@@@@@@        @@        @@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@        @@        @@@@@@@@@@
@@@@@@@@@@    @@  @@  @@@@  @@@@@@@@@@
@@@@@@@@@@    @@  @@  @@@@  @@@@@@@@@@
@@@@@@@@@@        @@  @  @  @@@@@@@@@@
@@@@@@@@@@        @@        @@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@  @@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@  Thank you for using jOOQ 3.11.9
                                      
```

Can you tell me what i am doing wrong? :|

**Comment by sebastian-raubach** [comment]
Are you using the Docker image or are you building the software yourself?

**Comment by brunopnogueira92** [comment]
> Are you using the Docker image or are you building the software yourself?

Building software by myself, in Windows with tomcat/mysql server

**Comment by sebastian-raubach** [comment]
Is there anything in Tomcat's command window or the `localhost.2020-07-15.log` or `catalina.2020-07-15.log` files?

**Comment by sebastian-raubach** [comment]
Also, check the browser dev tools and see if anything is printed to the console. Are any of the requests under the network tab failing? If so, what error code and what URL are they trying to request?

**Comment by brunopnogueira92** [comment]
I found this error in the web console:

`xhr.js:172 POST http://localhost:8090/%3Cproject.name%3E/v4.0.0/api/token 404`

```
createError.js:16 Uncaught (in promise) Error: Request failed with status code 404
    at e.exports (createError.js:16)
    at e.exports (settle.js:17)
    at XMLHttpRequest.h.onreadystatechange (xhr.js:59)
```

**Comment by brunopnogueira92** [comment]
I think i miss some configuration field :|

**Comment by sebastian-raubach** [comment]
During the configuration step of Gatekeeper Vue, you need to set a property in the `.env` file:

    VUE_APP_BASE_URL=/<project.name>/v4.0.0/api/

You can either set this to `./api/` or use the context of the deployed application within Tomcat `/<context>/v4.0.0/api/`. Make sure to replace `<context>` appropriately.

I think you mentioned that you managed to get Germinate up and running. It has a very similar step, so better go back and check your configuration there as well.

**Comment by brunopnogueira92** [comment]
Thank you so much, sorry for all this questions but i am a little bit newby =D

One more question:
In germinate-server configurations, to integrate the Gatekeeper, we have to put these three information:

```
gatekeeper.url                                  = <base url of gatekeeper if using>
gatekeeper.username                      = <username of gatekeeper if using>
gatekeeper.password                      = <password of gatekeeper if using and required>
```

I put that three information like these:
```
gatekeeper.url=http://localhost:8080/interpheno-gk/v4.0.0
gatekeeper.username=admin
gatekeeper.password=password
gatekeeper.registration.enabled=
```

With this configurations, it is supposed to appear the user icon in the top right corner, but nothing changed with this configuration. It's appear that Germinate no link to GateKeeper.

**Comment by sebastian-raubach** [comment]
You need to enable the authentication mode as well:

    # The authentication mode determines whether users have to log in or not.
    # NONE disables authentication (and the use of Gatekeeper).
    # FULL requires all users to log in before they can even see any data.
    # SELECTIVE only requires users to log in if they want to use any features that alter the database, e.g. creating groups, adding comments, etc.
    authentication.mode = <either 'SELECTIVE', 'FULL' or 'NONE'>

**Comment by brunopnogueira92** [comment]
> You need to enable the authentication mode as well:
> 
> ```
> # The authentication mode determines whether users have to log in or not.
> # NONE disables authentication (and the use of Gatekeeper).
> # FULL requires all users to log in before they can even see any data.
> # SELECTIVE only requires users to log in if they want to use any features that alter the database, e.g. creating groups, adding comments, etc.
> authentication.mode = <either 'SELECTIVE', 'FULL' or 'NONE'>
> ```
> 
> You'll probably want `SELECTIVE`.

Well i think i do something wrong.

No user icon appears. :-|

![germinate](https://user-images.githubusercontent.com/65361033/87654043-4c516280-c74e-11ea-9b0f-36217ce7e9dc.png)

**Comment by sebastian-raubach** [comment]
It looks like the client can't even connect to the server. Check the dev console in your browser again.
Did you check the `.env` setting of the Germinate client and rebuild and redeploy?

**Comment by brunopnogueira92** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/65361033/87654591-0ba61900-c74f-11ea-8101-1ee474fd2037.png)
![Screenshot_2](https://user-images.githubusercontent.com/65361033/87654704-37c19a00-c74f-11ea-8300-3f4636760346.png)

Yes, i found out that in Germinate i have a lot of errors.

I do not know why but for some reason, the file ".env" do not take no effect.
The content of the file is:

`VUE_APP_BASE_URL=/<project.name>/v4.0.3/api/`

I think i am configuring this with so much mistakes xD

**Comment by sebastian-raubach** [comment]
As mentioned before for Gatekeeper, you need to change this to something like:
`./api/` or use the context of the deployed application within Tomcat `/<context>/v4.0.3/api/`. Make sure to replace <context> appropriately.
`<project.name>` is just a placeholder and needs to be replaced accordingly.

**Comment by sebastian-raubach** [comment]
Are you not able to use the Docker image?

**Comment by brunopnogueira92** [comment]
> Are you not able to use the Docker image?

No unfortunately i have a Windows 10 Home version that not support docker hub. But eventually i have to deploy this stuff in university servers and i think they haven´t the content to run a docker image.

**Comment by brunopnogueira92** [comment]
> As mentioned before for Gatekeeper, you need to change this to something like:
> `./api/` or use the context of the deployed application within Tomcat `/<context>/v4.0.3/api/`. Make sure to replace appropriately.
> `<project.name>` is just a placeholder and needs to be replaced accordingly.

Sorry for this dummy question, but in .env file, i have to replace the <project.name> with something or the build process will replace it? Because, for the gatekeeper only works when i put the .env file with /api/.

(PS: the env that you see above is for germinate)

**Comment by sebastian-raubach** [comment]
It should be whatever you .war file is called within Tomcat plus `/v4.0.3/api/` if you want to use the absolute version, but it should work with `./api/` (mind the ".").

**Comment by sebastian-raubach** [comment]
The documentation states:

> Where `project.name` comes from the Germinate Server configuration below.

And then:

    project.name=<the relative path inside tomcat, e.g. 'germinate' -> http://localhost:8080/germinate/v4.0.3>

**Comment by sebastian-raubach** [comment]
Closed because of inactivity.
